# Generated by Django 4.2.3 on 2023-07-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowNum", models.TextField()),
                ("opnSfTeamCode", models.TextField()),
                ("mgtNo", models.TextField()),
                ("opnSvcId", models.TextField()),
                ("updateGbn", models.TextField()),
                ("updateDt", models.TextField()),
                ("opnSvcNm", models.TextField()),
                ("bplcNm", models.TextField()),
                ("sitePostNo", models.TextField()),
                ("siteWhlAddr", models.TextField()),
                ("rdnPostNo", models.TextField()),
                ("rdnWhlAddr", models.TextField()),
                ("siteArea", models.TextField()),
                ("apvPermYmd", models.TextField()),
                ("apvCancelYmd", models.TextField()),
                ("dcbYmd", models.TextField()),
                ("clgStdt", models.TextField()),
                ("clgEnddt", models.TextField()),
                ("ropnYmd", models.TextField()),
                ("trdStateGbn", models.TextField()),
                ("dtlStateGbn", models.TextField()),
                ("dtlStateNm", models.TextField()),
                ("x", models.TextField()),
                ("y", models.TextField()),
                ("lastModTs", models.TextField()),
                ("uptaeNm", models.TextField()),
                ("siteTel", models.TextField()),
            ],
        ),
    ]
